---
- name: Create Desktop Directory for Scanner Tools
  copy:
    content: |
      [Desktop Entry]
      Name=Scanner Tools
      Comment=Tools for scanning and enumeration
      Icon=scanner-tools
      Type=Directory
    dest: /usr/share/desktop-directories/ScannerTools.directory
    mode: '0644'

- name: Create Desktop Directory for Active Directory Tools
  copy:
    content: |
      [Desktop Entry]
      Name=Active Directory Tools
      Comment=Tools for managing and interacting with Active Directory
      Icon=active-directory-tools
      Type=Directory
    dest: /usr/share/desktop-directories/ActiveDirectoryTools.directory
    mode: '0644'

- name: Create Desktop Directory for Password Recovery Tools
  copy:
    content: |
      [Desktop Entry]
      Name=Password Recovery Tools
      Comment=Tools for recovering passwords and hashes
      Icon=password-recovery-tools
      Type=Directory
    dest: /usr/share/desktop-directories/PasswordRecoveryTools.directory
    mode: '0644'

- name: Create Desktop Directory for Web Tools
  copy:
    content: |
      [Desktop Entry]
      Name=Web Tools
      Comment=Tools for web development and testing
      Icon=web-tools
      Type=Directory
    dest: /usr/share/desktop-directories/WebTools.directory
    mode: '0644'

