---
- name: Create directory for wordlists
  become: true
  file:
    path: /opt/wordlist
    state: directory
    mode: '0755'

- name: Clone wordlists repository
  become: true
  git:
    repo: https://github.com/SourM1lk/wordlists.git
    dest: /opt/wordlist
    depth: 1

