---
- name: Create directory for Binary Ninja
  file:
    path: /opt/binaryninja
    state: directory
    mode: '0755'
  become: true

- name: Download Binary Ninja free installer
  get_url:
    url: https://cdn.binary.ninja/installers/binaryninja_free_linux.zip
    dest: /tmp/binaryninja_free_linux.zip

- name: Unzip Binary Ninja free installer
  unarchive:
    src: /tmp/binaryninja_free_linux.zip
    dest: /opt/binaryninja
    remote_src: yes
  become: true

- name: Create symlink for Binary Ninja
  file:
    src: /opt/binaryninja/binaryninja
    dest: /usr/local/bin/binaryninja
    state: link
  become: true

- name: Create Binary Ninja .desktop file
  copy:
    content: |
      [Desktop Entry]
      Name=Binary Ninja
      Comment=Binary Ninja
      Exec=binaryninja
      Icon=/usr/share/icons/sidekick.jpg
      Terminal=false
      Type=Application
      Categories=Development;
    dest: /usr/share/applications/binaryninja.desktop
    mode: '0644'
  become: true
