---
- name: Install NetExec using pipx
  pip:
    name: "git+https://github.com/Pennyw0rth/NetExec"
    executable: pipx

- name: Create NetExec .desktop file
  copy:
    content: |
      [Desktop Entry]
      Name=NetExec
      Comment=NetExec - Network Execution Tool
      Exec=/usr/bin/nxc
      Icon=/usr/share/icons/netexec.png
      Terminal=true
      Type=Application
      Categories=WebTools;
    dest: /usr/share/applications/netexec.desktop
    mode: '0644'