---
- name: Copy dotfiles to ~/.config using the `cp` command
  command: cp -r "{{ playbook_dir }}/dotfiles/.config/." "{{ lookup('env', 'HOME') }}/.config/"

- name: Copy alacritty.toml to ~/.config
  command: cp "{{ playbook_dir }}/dotfiles/.config/alacritty/alacritty.toml" "{{ lookup('env', 'HOME') }}/.config/alacritty.toml"
